"""
build_exe.py — Build & Package Universal Video Downloader
=========================================================
Step 1: PyInstaller  → creates standalone EXE in dist/
Step 2: Inno Setup   → wraps the EXE into a professional Windows installer

Usage:
    python build_exe.py

Requirements:
    - PyInstaller:  pip install pyinstaller
    - Inno Setup:   Download from https://jrsoftware.org/isdl.php (install to default path)
"""

import subprocess
import sys
import os
import shutil
import textwrap

# ── Config ───────────────────────────────────────────────────
APP_NAME = "Universal Video Downloader"
APP_VERSION = "1.3.8"
APP_PUBLISHER = "Devanshu"
APP_URL = "https://github.com/Devanshu138/UniversalVedioDownloader"
MAIN_SCRIPT = "gui_downloader.py"
ICON_FILE = "app.ico"  # App icon for EXE and installer
EXE_NAME = "UniversalVideoDownloader"

# Inno Setup compiler paths (tries both)
ISCC_PATHS = [
    r"A:\Inno Setup 6\ISCC.exe",
    r"C:\Program Files (x86)\Inno Setup 6\ISCC.exe",
    r"C:\Program Files\Inno Setup 6\ISCC.exe",
]

ROOT_DIR = os.path.dirname(os.path.abspath(__file__))
DIST_DIR = os.path.join(ROOT_DIR, "dist")
BUILD_DIR = os.path.join(ROOT_DIR, "build")
ISS_FILE = os.path.join(ROOT_DIR, "installer.iss")
OUTPUT_DIR = os.path.join(ROOT_DIR, "installer_output")


def step_pyinstaller():
    """Step 1: Bundle the app into a single-folder EXE with PyInstaller."""
    print("\n" + "=" * 60)
    print("  STEP 1: Building EXE with PyInstaller")
    print("=" * 60)

    # Clean previous builds
    for d in [DIST_DIR, BUILD_DIR]:
        if os.path.exists(d):
            shutil.rmtree(d)
            print(f"  Cleaned {d}")

    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--noconfirm",
        "--windowed",                    # No console window
        "--name", EXE_NAME,
        "--add-data", "README.md;.",     # Include README
    ]

    if ICON_FILE and os.path.exists(ICON_FILE):
        cmd += ["--icon", ICON_FILE]
        cmd += ["--add-data", f"{ICON_FILE};."]

    # Include hidden imports for download engines
    for mod in ["yt_dlp", "you_get", "streamlink", "customtkinter", "psutil"]:
        cmd += ["--hidden-import", mod]

    # CustomTkinter needs its data files
    try:
        import customtkinter
        ctk_path = os.path.dirname(customtkinter.__file__)
        cmd += ["--add-data", f"{ctk_path};customtkinter/"]
    except ImportError:
        print("  WARNING: customtkinter not found, the EXE may fail!")

    cmd.append(MAIN_SCRIPT)

    print(f"  Running: {' '.join(cmd[:6])}...")
    result = subprocess.run(cmd, cwd=ROOT_DIR)

    if result.returncode != 0:
        print("\n  ❌ PyInstaller FAILED! Check the output above.")
        sys.exit(1)

    exe_path = os.path.join(DIST_DIR, EXE_NAME, f"{EXE_NAME}.exe")
    if os.path.exists(exe_path):
        print(f"\n  ✅ EXE built successfully: {exe_path}")
    else:
        print(f"\n  ❌ EXE not found at expected path: {exe_path}")
        sys.exit(1)

    return exe_path


def step_inno_setup():
    """Step 2: Generate an Inno Setup script and compile it into an installer."""
    print("\n" + "=" * 60)
    print("  STEP 2: Creating Installer with Inno Setup")
    print("=" * 60)

    # Find ISCC.exe
    iscc = None
    for p in ISCC_PATHS:
        if os.path.exists(p):
            iscc = p
            break

    if not iscc:
        print("  ⚠️  Inno Setup not found! Skipping installer creation.")
        print("  Download it from: https://jrsoftware.org/isdl.php")
        print(f"  The .iss script has been saved to: {ISS_FILE}")
        print("  You can compile it manually later with ISCC.exe.")
        # Still generate the .iss file so the user can compile later
        _write_iss()
        return

    _write_iss()

    print(f"  Compiling with: {iscc}")
    result = subprocess.run([iscc, ISS_FILE])

    if result.returncode == 0:
        print(f"\n  ✅ Installer created in: {OUTPUT_DIR}")
    else:
        print("\n  ❌ Inno Setup compilation failed!")
        sys.exit(1)


def _write_iss():
    """Generate the Inno Setup .iss script."""
    icon_line = ""
    if ICON_FILE and os.path.exists(os.path.join(ROOT_DIR, ICON_FILE)):
        icon_line = f'SetupIconFile={os.path.join(ROOT_DIR, ICON_FILE)}'

    iss_content = textwrap.dedent(f"""\
        ; Inno Setup Script — Auto-generated by build_exe.py
        ; Do not edit manually unless you know what you're doing.

        [Setup]
        AppName={APP_NAME}
        AppVersion={APP_VERSION}
        AppPublisher={APP_PUBLISHER}
        AppPublisherURL={APP_URL}
        AppSupportURL={APP_URL}
        DefaultDirName={{autopf}}\\{APP_NAME}
        DefaultGroupName={APP_NAME}
        OutputDir={OUTPUT_DIR}
        OutputBaseFilename={EXE_NAME}_Setup_v{APP_VERSION}
        Compression=lzma2/ultra64
        SolidCompression=yes
        ArchitecturesAllowed=x64compatible
        ArchitecturesInstallIn64BitMode=x64compatible
        WizardStyle=modern
        DisableProgramGroupPage=yes
        PrivilegesRequired=lowest
        {icon_line}

        [Languages]
        Name: "english"; MessagesFile: "compiler:Default.isl"

        [Tasks]
        Name: "desktopicon"; Description: "Create a Desktop shortcut"; GroupDescription: "Additional shortcuts:"; Flags: unchecked

        [Files]
        Source: "{os.path.join(DIST_DIR, EXE_NAME, '*')}"; DestDir: "{{app}}"; Flags: ignoreversion recursesubdirs createallsubdirs

        [Icons]
        Name: "{{group}}\\{APP_NAME}"; Filename: "{{app}}\\{EXE_NAME}.exe"
        Name: "{{group}}\\Uninstall {APP_NAME}"; Filename: "{{uninstallexe}}"
        Name: "{{commondesktop}}\\{APP_NAME}"; Filename: "{{app}}\\{EXE_NAME}.exe"; Tasks: desktopicon

        [Run]
        Filename: "{{app}}\\{EXE_NAME}.exe"; Description: "Launch {APP_NAME}"; Flags: nowait postinstall skipifsilent
    """)

    with open(ISS_FILE, "w", encoding="utf-8") as f:
        f.write(iss_content)

    print(f"  Generated: {ISS_FILE}")


if __name__ == "__main__":
    print(f"\n{'=' * 60}")
    print(f"  {APP_NAME} — Build & Package Script")
    print(f"{'=' * 60}")

    step_pyinstaller()
    step_inno_setup()

    print(f"\n{'=' * 60}")
    print("  ALL DONE!")
    print(f"  EXE folder:  {os.path.join(DIST_DIR, EXE_NAME)}")
    print(f"  Installer:   {OUTPUT_DIR}")
    print(f"{'=' * 60}\n")
