; Inno Setup Script — Auto-generated by build_exe.py
; Do not edit manually unless you know what you're doing.

[Setup]
AppName=Universal Video Downloader
AppVersion=1.3.8
AppPublisher=Devanshu
AppPublisherURL=https://github.com/Devanshu138/UniversalVedioDownloader
AppSupportURL=https://github.com/Devanshu138/UniversalVedioDownloader
DefaultDirName={autopf}\Universal Video Downloader
DefaultGroupName=Universal Video Downloader
OutputDir=k:\Experiment\installer_output
OutputBaseFilename=UniversalVideoDownloader_Setup_v1.3.8
Compression=lzma2/ultra64
SolidCompression=yes
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
WizardStyle=modern
DisableProgramGroupPage=yes
PrivilegesRequired=lowest


[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Create a Desktop shortcut"; GroupDescription: "Additional shortcuts:"; Flags: unchecked

[Files]
Source: "k:\Experiment\dist\UniversalVideoDownloader\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\Universal Video Downloader"; Filename: "{app}\UniversalVideoDownloader.exe"
Name: "{group}\Uninstall Universal Video Downloader"; Filename: "{uninstallexe}"
Name: "{commondesktop}\Universal Video Downloader"; Filename: "{app}\UniversalVideoDownloader.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\UniversalVideoDownloader.exe"; Description: "Launch Universal Video Downloader"; Flags: nowait postinstall skipifsilent
